# Generated by Django 3.0.5 on 2020-04-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20200428_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
