# Generated by Django 3.0.5 on 2020-04-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_address_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='city',
            name='cp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
