# Generated by Django 3.0.5 on 2020-04-29 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20200429_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='city',
            name='cp',
        ),
        migrations.CreateModel(
            name='CP',
            fields=[
                ('cp', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.City')),
            ],
        ),
    ]
