# Generated by Django 3.0.5 on 2020-05-25 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_auto_20200429_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='colony',
        ),
        migrations.RemoveField(
            model_name='cp',
            name='city',
        ),
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cp',
            name='colony',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Colony'),
        ),
    ]
