# Generated by Django 3.0.5 on 2020-06-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_auto_20200528_2356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CP',
        ),
    ]
