# Generated by Django 3.0.5 on 2020-06-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_delete_cp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='colony',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
