# Generated by Django 3.0.5 on 2020-04-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='bank_account',
            field=models.FileField(upload_to='company/bank_account/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='constitutive_act',
            field=models.FileField(upload_to='company/constitutive_act/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='employer_registration',
            field=models.FileField(upload_to='company/employer_registration/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='estate',
            field=models.FileField(upload_to='company/state/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='proof_of_address',
            field=models.FileField(upload_to='company/proof_of_address/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='sat',
            field=models.FileField(upload_to='company/sat/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tax_certificate',
            field=models.FileField(upload_to='company/tax_certificate/'),
        ),
    ]
