# Generated by Django 3.0.5 on 2020-04-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200429_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmg', models.FileField(blank=True, null=True, upload_to='')),
                ('dgj', models.FileField(blank=True, null=True, upload_to='')),
                ('dgq', models.FileField(blank=True, null=True, upload_to='')),
                ('gnp', models.FileField(blank=True, null=True, upload_to='')),
                ('ngm', models.FileField(blank=True, null=True, upload_to='')),
                ('tmg', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
