# Generated by Django 3.0.5 on 2020-05-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companynda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
