# Generated by Django 3.0.5 on 2020-06-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200525_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='estate',
            new_name='estate_document',
        ),
    ]
