# Generated by Django 3.0.5 on 2020-06-13 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20200613_0119'),
        ('company', '0005_auto_20200612_0533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyNDA',
        ),
    ]
