# Generated by Django 3.0.5 on 2020-04-28 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ine', models.FileField(upload_to='')),
                ('power_letter', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_at', models.DateField(auto_now=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('last_name', models.CharField(max_length=50)),
                ('second_last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('telephone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('rfc', models.CharField(max_length=12)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
