# Generated by Django 3.0.5 on 2020-04-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='ine',
            field=models.FileField(upload_to='person/ine/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='power_letter',
            field=models.FileField(upload_to='person/power_letter/'),
        ),
    ]
