# Generated by Django 3.0.5 on 2020-06-23 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0006_auto_20200613_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petitionnda',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='person/nda/'),
        ),
        migrations.AlterField(
            model_name='petitionnda',
            name='petition_type',
            field=models.CharField(blank=True, choices=[('cmg', 'cmg'), ('dgj', 'dgj'), ('dgq', 'dgq'), ('gnp', 'gnp'), ('ngm', 'ngm'), ('tmg', 'tmg')], max_length=10, null=True),
        ),
    ]
